# Generated by Django 5.2.1 on 2025-07-10 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasa_service_app', '0002_tabledevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_cashier',
            new_name='is_admin_service',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_kitchen',
            new_name='is_technician',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_waitress',
        ),
        migrations.CreateModel(
            name='ServiceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Kode unik perangkat', max_length=20)),
                ('customer_name', models.CharField(help_text='Nama pelanggan', max_length=100)),
                ('device_type', models.CharField(help_text='Jenis perangkat (PC, Laptop, dll)', max_length=50)),
                ('brand', models.CharField(help_text='Merek perangkat', max_length=50)),
                ('damage_description', models.TextField(help_text='Deskripsi kerusakan')),
                ('service_status', models.CharField(choices=[('Masuk', 'Masuk'), ('Proses', 'Proses'), ('Selesai', 'Selesai'), ('Diambil', 'Diambil')], default='Masuk', max_length=20)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_create_service_device', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_service_device', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TableDevice',
        ),
    ]
