# Generated by Django 5.2.1 on 2025-07-22 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasa_service_app', '0004_customer_servicetype_sparepart_device_order_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedevice',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='servicedevice',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='servicedevice',
            name='device_type',
        ),
        migrations.AddField(
            model_name='servicedevice',
            name='customer',
            field=models.ForeignKey(default=1, help_text='Nama pelanggan', on_delete=django.db.models.deletion.CASCADE, to='jasa_service_app.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicedevice',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jasa_service_app.device'),
            preserve_default=False,
        ),
    ]
