# Generated by Django 5.2.1 on 2025-08-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasa_service_app', '0005_remove_servicedevice_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
